config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  namespace :admin do
    root to: 'top#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :posts, only: %i[index show edit update destroy]
  end
  root "top#index"
  get 'privacy_policy', to: 'top#privacy_policy'
  get 'terms_of_service', to: 'top#terms_of_service'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'google_login_api/callback', to: 'google_login_api#callback'
  post '/callback' => 'linebot#callback'
  resource :profile,only: %i[show edit update]
  resources :users, only: %i[new create destroy] do
    resource :password, only: %i[edit update]
    resources :favorite_zoos, only: %i[new create destroy]
  end
  resources :zoos, only: %i[index show] do
    collection do
      get 'map'
      get 'ranking'
      get "recommend"
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[index new create show edit update destroy] do
    resource :likes, only: %i[create destroy]
    collection do
      get 'ranking'
      get 'my_posts'
      get 'my_like_posts'
      get "stamp_rally"
    end
  end
end

app/models/favorite_zoo.rb
class FavoriteZoo < ApplicationRecord
  belongs_to :user
  belongs_to :zoo

  validates :rank, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3 }
  validate :validate_rank_uniqueness
  validate :validate_zoo_uniqueness

  private

  def validate_rank_uniqueness
    return unless rank.present? && user_id.present?
    existing_records = FavoriteZoo.where(user_id: user_id, rank: rank)
    errors.add(:rank, "はすでに登録されています") if existing_records.exists?
  end

  def validate_zoo_uniqueness
    return unless zoo_id.present? && user_id.present?
    existing_records = FavoriteZoo.where(user_id: user_id, zoo_id: zoo_id)
    errors.add(:zoo_id, "すでに登録されています") if existing_records.exists?
  end
end

app/controllers/favorite_zoos_controller.rb
class FavoriteZoosController < ApplicationController
  before_action :require_login
  before_action :set_user, only: %i[new create destroy]

  def new
    @favorite_zoo = @user.favorite_zoos.build
    @favorite_zoos = current_user.favorite_zoos.order(rank: :asc)
  end

  def create
    @favorite_zoo = @user.favorite_zoos.build(favorite_zoo_params)
    if @favorite_zoo.save
      redirect_to new_user_favorite_zoo_path(current_user), notice: t(".success_create_favotite_zoo")
    else
      @favorite_zoos = @user.favorite_zoos.order(rank: :asc)
      flash.now[:danger] = t(".fail_create_favotite_zoo")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @favorite_zoo = @user.favorite_zoos.find(params[:id])
    redirect_to new_user_favorite_zoo_path(current_user), notice: t(".success_delete_favotite_zoo") if @favorite_zoo.destroy!
  end

  private

  def favorite_zoo_params
    params.require(:favorite_zoo).permit(:zoo_id, :rank)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/views/favorite_zoos/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="main_image items-center justify-center text-center">
  <h1 class="text-3xl py-10"><%= t '.title' %></h1>
  <section class="main_image items-center justify-center text-center">
    <div class="container mx-auto">
      <div class="flex flex-wrap justify-center pb-10">
        <% if @posts.present? %>
          <%= render partial: 'posts/post', collection: @posts %>
        <% else %>
          <p class="text-2xl"><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/favorite_zoos/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="main_image">
  <div class="text-center">
    <div class="pt-20">
      <div class="md:grid justify-items-stretch">
        <div class="font-bold md:w-2/3 xl:w-1/3 justify-self-center text-4xl pb-20"><%= t('defaults.favorite_zoo') %></div>
        <div style="position: relative; text-align: center;" class="pb-10">
          <span style="display: flex; align-items: center; justify-content: center;" class="text-center text-xl">
            みんなのお気に入りの動物園の中からトップ3を登録してほしいゾゥ<br>
            ただし、注意点が3つあるゾゥ<br>
            ・1つの順位に対して、1つしか動物園は登録できないゾゥ<br>
            ・1つの動物園は、複数の順位には登録できないゾゥ<br>
            ・お気に入りを変更する場合は、1度削除してから再度登録してほしいゾゥ<br>
          </span>
          <%= image_tag "animalface_zou.png", class: "message-image w-16 rounded-full mx-auto" %>
        </div>
        <% if @user.favorite_zoos.count < 3 %>
          <div class="main_image flex items-center justify-center text-center pb-10">
            <%= form_with(model: [@user, @favorite_zoo], url: user_favorite_zoos_path(@user)) do |f| %>
              <%= render 'shared/error_messages', object: f.object %>
              <div class="flex flex-col items-center text-2xl pb-10">
                <%= f.label :rank %>
                <%= f.select :rank, (1..3).to_a, { prompt: "順位を選択してください" }, class: 'input input-bordered input-primary', style: 'width: 220px;' %>
              </div>
              <div class="flex flex-col items-center text-2xl">
                <%= f.label :zoo_id %>
                <%= f.collection_select :zoo_id, Zoo.all, :id, :name, { prompt: "動物園を選択してください" }, class: 'input input-bordered input-primary', style: 'width: 320px;' %>
              </div>
              <%= f.submit class: "btn btn-primary text-white font-bold my-10" %>
            <% end %>
          </div>
        <% end %>
        <div class="items-center justify-center text-center">
          <% @favorite_zoos.each do |favorite_zoo| %>
            <div class="flex items-center justify-center text-center mb-10">
              <div class="text-2xl link link-primary pr-2">
                第<%= favorite_zoo.rank %>位 <%= link_to favorite_zoo.zoo.name, zoo_path(favorite_zoo.zoo) %>
              </div>
              <%= link_to t('defaults.destroy'), user_favorite_zoo_path(current_user, favorite_zoo), data: { turbo_method: :delete, "turbo-confirm": (t 'defaults.destroy?') }, class: "btn btn-neutral text-white" %>
            </div>
          <% end %>
          <% if current_user.favorite_zoos.present? %>
            <%= link_to "https://twitter.com/share?url=https://www.zoomania.top/zoos/ranking/&text=#{current_user.name}さんがお気に入りの動物園を登録しました！%0A&hashtags=ZooMania", class: 'btn btn-secondary text-white mb-20', target: '_blank' do %>
              <i class="fab fa-twitter fa-2xl"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>