config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  namespace :admin do
    root to: 'top#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :posts, only: %i[index show edit update destroy]
  end
  root "top#index"
  get 'privacy_policy', to: 'top#privacy_policy'
  get 'terms_of_service', to: 'top#terms_of_service'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'google_login_api/callback', to: 'google_login_api#callback'
  post '/callback' => 'linebot#callback'
  resource :profile,only: %i[show edit update]
  resources :users, only: %i[new create destroy] do
    resource :password, only: %i[edit update]
    resources :favorite_zoos, only: %i[new create destroy]
  end
  resources :zoos, only: %i[index show] do
    collection do
      get 'map'
      get 'ranking'
      get "recommend"
    end
  end
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[index new create show edit update destroy] do
    resource :likes, only: %i[create destroy]
    collection do
      get 'ranking'
      get 'my_posts'
      get 'my_like_posts'
      get "stamp_rally"
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="main_image text-brown font-bold pb-10">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> main_image text-brown font-bold pt-10 pl-10" style="background-color: inherit; border: none;">
        <div class="avatar">
            <div class="w-16 rounded-full">
                <%= image_tag "animalface_zou.png", class: "message-image" %>
            </div>
        </div>
        <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer_image relative py-10">
  <div class="md:ml-auto flex flex-wrap justify-center text-white pb-10">
    <%= link_to (t 'top.privacy_policy.title'), privacy_policy_path, class: "link link-hover text-white text-lg mx-2" %>
    <%= link_to (t 'top.terms_of_service.title'), terms_of_service_path, class: "link link-hover text-white text-lg mx-2" %>
    <%= link_to (t "defaults.inquiry"), "https://forms.gle/Xay1BB4VppFYwK2FA", target: :_blank, rel: "noopener noreferrer", class: "link link-hover text-white text-lg mx-2" %>
  </div>
  <div class="justify-center text-center mx-auto w-36 pb-10" style="display: flex; justify-content: center; align-items: center;">
  <a href="https://lin.ee/K5xZIFE">
    <img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0">
  </a>
</div>
  <p class="text-center text-white">&copy; 2023 ZooMania</p>
</footer>

app/views/shared/_header.html.erb
<header class="bg-main">
  <div class="container mx-auto flex flex-wrap flex-col md:flex-row items-center py-2">
    <%= link_to image_tag('logo_cut.jpg', size: '100x100'), root_path, class: "py-1" %>
    <div class="md:ml-auto flex flex-wrap items-center md:text-xl justify-center">
      <div class="dropdown dropdown-hover mx-1">
        <label tabindex="0" class="btn btn-primary text-white">動物園</label>
        <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
          <%= link_to (t 'zoos.index.title'), zoos_path, class: "btn btn-primary text-white my-1" %>
          <%= link_to (t 'zoos.map.title'), map_zoos_path, class: "btn btn-primary text-white my-1" %>
          <%= link_to (t 'zoos.ranking.title'), ranking_zoos_path, class: "btn btn-primary text-white my-1" %>
          <%= link_to (t 'zoos.recommend.title'), recommend_zoos_path, class: "btn btn-primary text-white my-1" %>
        </ul>
      </div>
      <div class="dropdown dropdown-hover mx-1">
        <label tabindex="0" class="btn btn-primary text-white">投稿</label>
        <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
          <% if logged_in? %>
            <%= link_to (t 'posts.new.title'), new_post_path, class: "btn btn-primary text-white my-1" %>
          <% end %>
          <%= link_to (t 'posts.index.title'), posts_path, class: "btn btn-primary text-white my-1" %>
          <%= link_to (t 'posts.ranking.title'), ranking_posts_path, class: "btn btn-primary text-white my-1" %>
        </ul>
      </div>
      <% if logged_in? %>
        <div class="dropdown dropdown-hover dropdown-end">
          <label tabindex="0" class="btn mx-1" style="background-color: transparent; border: none;">
            <div class="avatar">
              <div class="w-16 rounded-full">
                <%= image_tag current_user.avatar.url %>
              </div>
            </div>
          </label>
          <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
            <%= link_to (t "profiles.show.title"), profile_path, class: "btn btn-primary text-white my-1" %>
            <%= link_to (t "favorite_zoos.new.title"), new_user_favorite_zoo_path(current_user), class: "btn btn-primary text-white my-1" %>
            <%= link_to (t "posts.my_posts.title"), my_posts_posts_path, class: "btn btn-primary text-white my-1" %>
            <%= link_to (t "posts.my_like_posts.title"), my_like_posts_posts_path, class: "btn btn-primary text-white my-1" %>
            <%= link_to (t "posts.stamp_rally.title"), stamp_rally_posts_path, class: "btn btn-primary text-white my-1" %>
            <% if current_user.admin? %>
              <%= link_to (t "defaults.admin_page"), admin_root_path, class: "btn btn-primary text-white my-1" %>
            <% end %>
            <%= link_to (t 'defaults.logout'), logout_path, data: { turbo_method: :delete, "turbo-confirm": (t 'defaults.logout?') }, class: "btn btn-primary text-white my-1" %>
          </ul>
      <% else %>
        <%= link_to (t 'defaults.loginpage'), login_path, class: "btn btn-primary text-white mx-1"%>
        <%= link_to (t 'defaults.register_page'), new_user_path, class: "btn btn-primary text-white mx-1"%>
      <% end %>
    </div>
  </div>
</header>